project_name: appknox
release:
  name_template: "Appknox CLI {{.Version}}"
  footer: |
    ### For installing in Linux & OSX:
    ```
    curl -L https://github.com/appknox/appknox-go/releases/download/{{.Version}}/appknox-`uname -s`-`uname -m` > /usr/local/bin/appknox && chmod +x /usr/local/bin/appknox
    ```

before:
  hooks:
    - make clean
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - format: binary
    name_template: >-
      {{- .ProjectName }}-
      {{- title .Os }}-
      {{- if eq .Os "darwin" }}
        {{- if eq .Arch "amd64" }}x86_64{{- end}}
        {{- if eq .Arch "arm64" }}arm64{{- end}}
      {{- end}}
      {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64" }}x86_64{{- end}}
      {{- end }}
      {{- if eq .Os "linux" }}
          {{- if eq .Arch "amd64" }}x86_64{{- end}}
          {{- if eq .Arch "arm64" }}aarch64{{- end}}
      {{- end }}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

nfpms:
  - vendor: Appknox
    maintainer: Appknox <engineering@appknox.com>
    homepage: https://github.com/appknox/appknox-go
    description: Appknox CLI tool.
    file_name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    formats:
      - deb
      - rpm
