version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/appknox/appknox-go
    steps:
      - checkout
      - run: make
      - run: make test_coverage
      - codecov/upload:
            file: coverage.txt
